name: CICD

on: [push]

jobs:
  php74-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: 7.4
          php_extensions: zip
          version: 2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 7.4
          php_extensions: zip
          bootstrap: test/bootstrap.php
          configuration: test/phpunit.xml
  php80-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: 8.0
          php_extensions: zip
          version: 2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_version: 8.0
          php_extensions: zip
          bootstrap: test/bootstrap.php
          configuration: test/phpunit.xml